# Generated by Django 5.2.8 on 2025-11-13 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_category_icon_alter_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='passed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='percentage',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'order'], name='quizzes_cat_is_acti_a719ce_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='quizzes_cat_slug_bca87c_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'is_active'], name='quizzes_sub_categor_38e0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='quizzes_use_attempt_5266f7_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizattempt',
            index=models.Index(fields=['user', 'completed'], name='quizzes_use_user_id_47ebe5_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizattempt',
            index=models.Index(fields=['user', 'completed_at'], name='quizzes_use_user_id_267e32_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizattempt',
            index=models.Index(fields=['user', 'passed'], name='quizzes_use_user_id_e1679a_idx'),
        ),
        migrations.AddIndex(
            model_name='userquizattempt',
            index=models.Index(fields=['-percentage'], name='quizzes_use_percent_1abf72_idx'),
        ),
    ]
