# Generated by Django 5.2.8 on 2025-11-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_on_leaderboard',
            field=models.BooleanField(default=False, help_text='Allow your username to appear on the public leaderboard'),
        ),
    ]
