# Generated by Django 5.2.8 on 2025-11-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_leaderboard_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='theme',
        ),
    ]
